services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
